name: Publish To Heroku 
description: Action to publish code with heroku
icon: cpu
color: blue
on:
  push:
    branches:
      - master
jobs:
  backend-heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login heroku 
      run: echo -e "machine api.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}\nmachine git.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}">~/.netrc
      env:
        EMAIL: ${{secrets.EMAIL_ORG}}
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    - name: add remote
      run: git remote add herokuback https://git.heroku.com/${HEROKU_BACKEND_APP_NAME}.git
      env:
        HEROKU_BACKEND_APP_NAME: ${{secrets.HEROKU_BACKEND_APP_NAME}}
    - name: push
      run: git subtree push --prefix ${JOURNEY_BACKEND_PATH} herokuback master
      env:
        JOURNEY_BACKEND_PATH=${{secrets.JOURNEY_BACKEND_PATH}}
  frontend-heroku:
    needs: backend-heroku
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login heroku 
      run: echo -e "machine api.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}\nmachine git.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}">~/.netrc
      env:
        EMAIL: ${{secrets.EMAIL_ORG}}
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    - name: add frontend remote
      run: git remote add herokufront https://git.heroku.com/${HEROKU_FRONTEND_APP_NAME}.git
      env:
        HEROKU_FRONTEND_APP_NAME: ${{secrets.HEROKU_FRONTEND_APP_NAME}}
    - name: push
      run: git subtree push --prefix ${JOURNEY_FRONTEND_PATH} herokufront master
      env:
        JOURNEY_FRONTEND_PATH=${{secrets.JOURNEY_FRONTEND_PATH}}